### ISSUE TITLE
`conf.int` not working for glmmTMB objects

### ISSUE THREAD

**Issue by strengejacke** [bbolker/broom.mixed#31]
``` r
library(glmmTMB)
library(broom.mixed)

m1 <- glmmTMB(count~ mined + (1|site), 
              zi=~mined, 
              family=poisson, data=Salamanders)

broom.mixed::tidy(m1, conf.int = TRUE, conf.level = .95)
#> Error in ci[parm, , drop = FALSE]: subscript out of bounds

broom.mixed::tidy(m1, conf.int = TRUE, conf.level = .5)
#> Error in ci[parm, , drop = FALSE]: subscript out of bounds
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bbolker** [comment]
should be fixed: c9d18c8b7e6

**Comment by strengejacke** [comment]
Is this really fixed? I just installed from GitHub, and the issue is still there... Or do I need to install from a specific branch?

**Comment by strengejacke** [comment]
ok, just saw there is only one branch.

**Comment by strengejacke** [comment]
``` r
library(glmmTMB)
library(broom.mixed)
data(Owls)

m1 <- glmmTMB(SiblingNegotiation ~ SexParent + ArrivalTime + (1 | Nest), data = Owls, family = nbinom1)
broom.mixed::tidy(m1, conf.int = TRUE)
#> Error in ci[parm, , drop = FALSE]: subscript out of bounds
```

<sup>Created on 2018-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.2.0        broom.mixed_0.2.2.9000

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4 TMB_1.7.14       reshape2_1.4.3   purrr_0.2.5      splines_3.5.1   
 [6] lattice_0.20-35  htmltools_0.3.6  yaml_2.2.0       base64enc_0.1-3  utf8_1.1.4      
[11] rlang_0.2.2      nloptr_1.2.1     pillar_1.3.0     glue_1.3.0       bindrcpp_0.2.2  
[16] bindr_0.1.1      plyr_1.8.4       stringr_1.3.1    coda_0.19-2      evaluate_0.12   
[21] knitr_1.20       callr_3.0.0      pscl_1.5.2       ps_1.1.0         fansi_0.4.0     
[26] broom_0.5.0      Rcpp_0.12.19     clipr_0.4.1      backports_1.1.2  debugme_1.1.0   
[31] fs_1.2.6         lme4_1.1-18-1    digest_0.6.17    stringi_1.2.4    processx_3.2.0  
[36] dplyr_0.7.6      grid_3.5.1       rprojroot_1.3-2  cli_1.0.1        tools_3.5.1     
[41] magrittr_1.5     tibble_1.4.2     crayon_1.3.4     tidyr_0.8.1      whisker_0.3-2   
[46] pkgconfig_2.0.2  MASS_7.3-50      Matrix_1.2-14    reprex_0.2.1     assertthat_0.2.0
[51] minqa_1.2.4      rmarkdown_1.10   rstudioapi_0.8   R6_2.3.0         nlme_3.1-137    
[56] compiler_3.5.1  
> 
```

**Comment by bbolker** [comment]
Weird. There is [a test for this](https://github.com/bbolker/broom.mixed/blob/master/tests/testthat/test-glmmTMB.R#L40), but *I disabled it for r-release*; I thought it must be some sort of glmmTMB problem, but maybe it's weirder/deeper than that? I'll try re-installing the CRAN version of  `glmmTMB` and see if I can get it to break so I can see where the problem is ....

```
R Under development (unstable) (2018-07-26 r75007)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_CA.UTF8       LC_NUMERIC=C             
 [3] LC_TIME=en_CA.UTF8        LC_COLLATE=en_CA.UTF8    
 [5] LC_MONETARY=en_CA.UTF8    LC_MESSAGES=en_CA.UTF8   
 [7] LC_PAPER=en_CA.UTF8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_CA.UTF8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] broom.mixed_0.2.2.9000 glmmTMB_0.2.2.9000    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19     pillar_1.3.0     compiler_3.6.0   nloptr_1.2.1    
 [5] plyr_1.8.4       TMB_1.7.14       bindr_0.1.1      tools_3.6.0     
 [9] lme4_1.1-18.9000 tibble_1.4.2     nlme_3.1-137     lattice_0.20-35 
[13] pkgconfig_2.0.2  rlang_0.2.2      Matrix_1.2-14    cli_1.0.1       
[17] bindrcpp_0.2.2   coda_0.19-2      dplyr_0.7.6      stringr_1.3.1   
[21] grid_3.6.0       tidyselect_0.2.4 glue_1.3.0       R6_2.3.0        
[25] fansi_0.4.0      minqa_1.2.4      purrr_0.2.5      tidyr_0.8.1     
[29] reshape2_1.4.3   magrittr_1.5     backports_1.1.2  MASS_7.3-50     
[33] splines_3.6.0    assertthat_0.2.0 utf8_1.1.4       stringi_1.2.4   
[37] broom_0.5.0      crayon_1.3.4  
```

**Comment by strengejacke** [comment]
Where is the code that causes the error? In broom.mixed, glmmTMB, lme4... ?
But all packages are up to date (except broom.mixed, for which I installed the GitHub version)

**Comment by strengejacke** [comment]
Ok, I just tested from another machine, with the current (from this minute) GitHub install of _broom.mixed_, and still get this error:

``` r
library(glmmTMB)
library(broom.mixed)

m1 <- glmmTMB(count~ mined + (1|site), 
              zi=~mined, 
              family=poisson, data=Salamanders)

broom.mixed::tidy(m1, conf.int = TRUE, conf.level = .95)
#> Error in ci[parm, , drop = FALSE]: subscript out of bounds

devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2018-10-13
#> Packages -----------------------------------------------------------------
#>  package     * version    date       source                              
#>  assertthat    0.2.0      2017-04-11 CRAN (R 3.5.0)                      
#>  backports     1.1.2      2017-12-13 CRAN (R 3.5.0)                      
#>  base        * 3.5.1      2018-07-02 local                               
#>  bindr         0.1.1      2018-03-13 CRAN (R 3.5.0)                      
#>  bindrcpp      0.2.2      2018-03-29 CRAN (R 3.5.0)                      
#>  broom         0.5.0      2018-07-17 CRAN (R 3.5.1)                      
#>  broom.mixed * 0.2.2.9000 2018-10-13 Github (bbolker/broom.mixed@1c73c8b)
#>  coda          0.19-2     2018-10-08 CRAN (R 3.5.1)                      
#>  compiler      3.5.1      2018-07-02 local                               
#>  crayon        1.3.4      2017-09-16 CRAN (R 3.5.0)                      
#>  datasets    * 3.5.1      2018-07-02 local                               
#>  devtools      1.13.6     2018-06-27 CRAN (R 3.5.0)                      
#>  digest        0.6.18     2018-10-10 CRAN (R 3.5.1)                      
#>  dplyr         0.7.6      2018-06-29 CRAN (R 3.5.1)                      
#>  evaluate      0.12       2018-10-09 CRAN (R 3.5.1)                      
#>  glmmTMB     * 0.2.2.0    2018-07-03 CRAN (R 3.5.1)                      
#>  glue          1.3.0      2018-07-17 CRAN (R 3.5.1)                      
#>  graphics    * 3.5.1      2018-07-02 local                               
#>  grDevices   * 3.5.1      2018-07-02 local                               
#>  grid          3.5.1      2018-07-02 local                               
#>  htmltools     0.3.6      2017-04-28 CRAN (R 3.5.0)                      
#>  knitr         1.20       2018-02-20 CRAN (R 3.5.0)                      
#>  lattice       0.20-35    2017-03-25 CRAN (R 3.5.0)                      
#>  lme4          1.1-18-1   2018-08-17 CRAN (R 3.5.1)                      
#>  magrittr      1.5        2014-11-22 CRAN (R 3.5.0)                      
#>  MASS          7.3-50     2018-04-30 CRAN (R 3.5.0)                      
#>  Matrix        1.2-14     2018-04-13 CRAN (R 3.5.0)                      
#>  memoise       1.1.0      2017-04-21 CRAN (R 3.5.0)                      
#>  methods     * 3.5.1      2018-07-02 local                               
#>  minqa         1.2.4      2014-10-09 CRAN (R 3.5.0)                      
#>  nlme          3.1-137    2018-04-07 CRAN (R 3.5.0)                      
#>  nloptr        1.2.1      2018-10-03 CRAN (R 3.5.1)                      
#>  pillar        1.3.0      2018-07-14 CRAN (R 3.5.1)                      
#>  pkgconfig     2.0.2      2018-08-16 CRAN (R 3.5.1)                      
#>  plyr          1.8.4      2016-06-08 CRAN (R 3.5.1)                      
#>  purrr         0.2.5      2018-05-29 CRAN (R 3.5.1)                      
#>  R6            2.3.0      2018-10-04 CRAN (R 3.5.1)                      
#>  Rcpp          0.12.19    2018-10-01 CRAN (R 3.5.1)                      
#>  reshape2      1.4.3      2017-12-11 CRAN (R 3.5.0)                      
#>  rlang         0.2.2      2018-08-16 CRAN (R 3.5.1)                      
#>  rmarkdown     1.10       2018-06-11 CRAN (R 3.5.0)                      
#>  rprojroot     1.3-2      2018-01-03 CRAN (R 3.5.0)                      
#>  splines       3.5.1      2018-07-02 local                               
#>  stats       * 3.5.1      2018-07-02 local                               
#>  stringi       1.2.4      2018-07-20 CRAN (R 3.5.1)                      
#>  stringr       1.3.1      2018-05-10 CRAN (R 3.5.0)                      
#>  tibble        1.4.2      2018-01-22 CRAN (R 3.5.0)                      
#>  tidyr         0.8.1      2018-05-18 CRAN (R 3.5.0)                      
#>  tidyselect    0.2.5      2018-10-11 CRAN (R 3.5.1)                      
#>  TMB           1.7.14     2018-06-23 CRAN (R 3.5.0)                      
#>  tools         3.5.1      2018-07-02 local                               
#>  utils       * 3.5.1      2018-07-02 local                               
#>  withr         2.1.2      2018-03-15 CRAN (R 3.5.0)                      
#>  yaml          2.2.0      2018-07-25 CRAN (R 3.5.1)
```

<sup>Created on 2018-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I just saw, if you use

```r
broom.mixed::tidy(m1, conf.int = TRUE, conf.level = .95, effects = "fixed")
```

it works fine. So `effects = "ran_pars"` causes the error, and if I checked your code right (see here https://github.com/bbolker/broom.mixed/blob/1c73c8b1a877de9dba0af5000dc917cb249bb729/R/glmmTMB_tidiers.R#L113 and following lines), `ret` is not initialised.

**Comment by bbolker** [comment]
thank you for tracking this down!  It  was fairly easy to put in some conditional logic that will (I hope) fix it. It works on r-release on Travis now, where it was failing before ... can you please confirm that it's fixed on your end?

**Comment by bbolker** [comment]
@strengejacke : feel free to chime in on #38 ...

**Comment by strengejacke** [comment]
Yes, works for me now!
I'll check the current GitHub-version on various models I use for testing my functions, and see if I find something to add to #38.

But you have addressed a lot of issues in the past weeks, so I'm not sure if I have currently something more to add. ;-)

**Comment by rpmady** [comment]
Hello,

I am finding that I have the same issue. I get "Error in ci[parm, , drop = FALSE] : subscript out of bounds" when I try to run the code 
`> confnitfixed <- confint(zipmodel_focal4, parm = "beta_", level=0.95, method = "Wald") 
`
